# Generated by Django 5.0.6 on 2025-10-16 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('rm', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('turma', models.CharField(max_length=6)),
                ('data_nasc', models.DateField(max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_envio', models.DateField(max_length=10)),
                ('cpf_autor', models.CharField(max_length=11)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Doações',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rf', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NI', 'Não Iniciado'), ('EA', 'Em Andamento'), ('FI', 'Finalizado')], default='NI', max_length=2)),
                ('desc', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='AlunoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('data_envio', models.DateField(max_length=10)),
                ('conteudo', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Sugestões',
            },
        ),
        migrations.CreateModel(
            name='ProjetoVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='main.projeto')),
            ],
            options={
                'unique_together': {('projeto', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='ResponsavelDependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes_responsavel', to='main.aluno')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='main.responsavel')),
            ],
            options={
                'unique_together': {('responsavel', 'dependente')},
            },
        ),
    ]
