# Generated by Django 5.0.6 on 2025-10-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='data_envio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
