# Generated by Django 5.0.6 on 2025-10-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuncionarioToken',
        ),
    ]
