# Generated by Django 5.1.1 on 2024-09-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_funcionario_id_alter_funcionario_rf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rm',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
