# Generated by Django 5.0.6 on 2024-10-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projeto_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotaFiscal',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rm',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
