# Generated by Django 5.0.6 on 2024-10-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0007_responsavel_rm_dependente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='rm_dependente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dependente', to='main.aluno'),
        ),
        migrations.CreateModel(
            name='ProjetoVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='main.projeto')),
            ],
            options={
                'unique_together': {('projeto', 'content_type', 'object_id')},
            },
        ),
    ]
