# Generated by Django 5.0.6 on 2024-10-17 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0008_alter_responsavel_rm_dependente_projetovoluntario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugestao',
            name='cpf_autor',
        ),
        migrations.AddField(
            model_name='sugestao',
            name='content_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sugestao',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
