# Generated by Django 5.0.6 on 2024-10-22 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0009_remove_sugestao_cpf_autor_sugestao_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelDependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='main.responsavel')),
            ],
            options={
                'unique_together': {('responsavel', 'content_type', 'object_id')},
            },
        ),
    ]
