# Generated by Django 5.0.6 on 2024-10-22 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_responsaveldependente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responsaveldependente',
            unique_together={('responsavel', 'dependente')},
        ),
        migrations.AddField(
            model_name='responsaveldependente',
            name='dependente',
            field=models.OneToOneField(default='90135', on_delete=django.db.models.deletion.CASCADE, to='main.aluno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsaveldependente',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='main.responsavel'),
        ),
        migrations.RemoveField(
            model_name='responsaveldependente',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='responsaveldependente',
            name='object_id',
        ),
    ]
