# Generated by Django 5.0.6 on 2024-10-28 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_responsaveldependente_dependente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='rm_dependente',
        ),
        migrations.AlterField(
            model_name='responsaveldependente',
            name='dependente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes_responsavel', to='main.aluno'),
        ),
        migrations.AlterField(
            model_name='responsaveldependente',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='main.responsavel'),
        ),
    ]
