# Generated by Django 5.1.1 on 2024-09-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doacoes',
            new_name='Doacao',
        ),
        migrations.RenameModel(
            old_name='Projetos',
            new_name='Projeto',
        ),
        migrations.RenameModel(
            old_name='Sugestoes',
            new_name='Sugestao',
        ),
        migrations.AlterModelOptions(
            name='doacao',
            options={'verbose_name_plural': 'Doações'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='responsavel',
            options={'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='sugestao',
            options={'verbose_name_plural': 'Sugestões'},
        ),
    ]
